sudo: false
dist: trusty
language: java

before_install:
  - pip install --user codecov

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - oraclejdk11

after_success:
  - mvn clean test jacoco:report coveralls:report
  - codecov
